[package]
name = "hack-emulator"
version = "0.1.0"
authors = ["lsaa <lsaadev.personal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nfd = "0.0.4"
olc_pixel_game_engine= "0.5.0"