use olc_pixel_game_engine as olc;

pub const INPUTS: [(olc::Key, char, char); 47] = [
    (olc::Key::A, 'a', 'A'),
    (olc::Key::B, 'b', 'B'),
    (olc::Key::C, 'c', 'C'),
    (olc::Key::D, 'd', 'D'),
    (olc::Key::E, 'e', 'E'),
    (olc::Key::F, 'f', 'F'),
    (olc::Key::G, 'g', 'G'),
    (olc::Key::H, 'h', 'H'),
    (olc::Key::I, 'i', 'I'),
    (olc::Key::J, 'j', 'J'),
    (olc::Key::K, 'k', 'K'),
    (olc::Key::L, 'l', 'L'),
    (olc::Key::M, 'm', 'M'),
    (olc::Key::N, 'n', 'N'),
    (olc::Key::O, 'o', 'O'),
    (olc::Key::P, 'p', 'P'),
    (olc::Key::Q, 'q', 'Q'),
    (olc::Key::R, 'r', 'R'),
    (olc::Key::S, 's', 'S'),
    (olc::Key::T, 't', 'T'),
    (olc::Key::U, 'u', 'U'),
    (olc::Key::V, 'v', 'V'),
    (olc::Key::W, 'w', 'W'),
    (olc::Key::X, 'x', 'X'),
    (olc::Key::Y, 'y', 'Y'),
    (olc::Key::Z, 'z', 'Z'),
    (olc::Key::K0, '0', ')'),
    (olc::Key::K1, '1', '!'),
    (olc::Key::K2, '2', '@'),
    (olc::Key::K3, '3', '#'),
    (olc::Key::K4, '4', '$'),
    (olc::Key::K5, '5', '%'),
    (olc::Key::K6, '6', '^'),
    (olc::Key::K7, '7', '&'),
    (olc::Key::K8, '8', '*'),
    (olc::Key::K9, '9', '('),
    (olc::Key::NP_MUL, '*', '*'),
    (olc::Key::NP_DIV, '/', '/'),
    (olc::Key::NP_ADD, '+', '+'),
    (olc::Key::NP_SUB, '-', '-'),
    (olc::Key::NP_DECIMAL, '.', '.'),
    (olc::Key::PERIOD, '.', '>'),
    (olc::Key::SPACE, ' ', ' '),
    (olc::Key::LEFT, 130 as char, 130 as char),
    (olc::Key::UP, 131 as char, 131 as char),
    (olc::Key::RIGHT, 132 as char, 132 as char),
    (olc::Key::DOWN, 133 as char, 133 as char),
];